//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int booking_id { get; set; }
        public int employee_id { get; set; }
        public int client_id { get; set; }
        public int room_id { get; set; }
        public int tarif_id { get; set; }
        public System.DateTime booking_date_issue { get; set; }
        public int booking_count_days { get; set; }
        public System.DateTime booking_date_departure { get; set; }
        public int booking_count_persons { get; set; }
        public int booking_count_childrens { get; set; }
        public string booking_comment { get; set; }
        public int booking_status_id { get; set; }
        public decimal booking_total_cost { get; set; }
        public Nullable<decimal> booking_prepayment { get; set; }
    
        public virtual booking_status booking_status { get; set; }
        public virtual clients clients { get; set; }
        public virtual employees employees { get; set; }
        public virtual rooms rooms { get; set; }
        public virtual tarifs tarifs { get; set; }
        public string RoomTypeName
        {
            get { return rooms?.room_type1?.room_type_name; }
        }
    }
}
