//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProgram
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clients()
        {
            this.additional_orders = new HashSet<additional_orders>();
            this.booking = new HashSet<booking>();
            this.documents = new HashSet<documents>();
        }
    
        public int client_id { get; set; }
        public Nullable<int> client_rating_id { get; set; }
        public string client_lastname { get; set; }
        public string client_name { get; set; }
        public string client_surname { get; set; }
        public string client_contact_number { get; set; }
        public string client_email { get; set; }
        public string client_address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<additional_orders> additional_orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> booking { get; set; }
        public virtual client_rating client_rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documents> documents { get; set; }
        public string ClientRatingName => client_rating?.client_rating_name;
        public int? ClientRatingCountOrders => client_rating?.client_rating_count_orders;
        public decimal? ClientRatingDiscount => client_rating?.client_rating_discount;

        public string DocumentTypes => string.Join(", ", documents.Select(d => d.document_types.document_type_name));
        public string DocumentNumbers => string.Join(", ", documents.Select(d => d.document_number));
        public string DocumentDates => string.Join(", ", documents.Select(d => d.document_date.ToShortDateString()));
        public string FullName
        {
            get
            {
                return $"{client_lastname} {client_name} {client_surname}";
            }
        }
    }
}
