//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employees()
        {
            this.additional_orders = new HashSet<additional_orders>();
            this.booking = new HashSet<booking>();
            this.transaction = new HashSet<transaction>();
        }
    
        public int employee_id { get; set; }
        public string employee_lastname { get; set; }
        public string employee_name { get; set; }
        public int employee_department { get; set; }
        public string employee_email { get; set; }
        public string employee_contact_number { get; set; }
        public string employee_surname { get; set; }
        public int Id { get; set; }
        public Nullable<int> company_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<additional_orders> additional_orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> booking { get; set; }
        public virtual company company { get; set; }
        public virtual department department { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transaction { get; set; }
        public string EmployeeFullName
        {
            get
            {
                return $"{employee_lastname} {employee_name} {employee_surname}";
            }
        }
    }
}
