//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public room_type()
        {
            this.rooms = new HashSet<rooms>();
        }
    
        public int room_type_id { get; set; }
        public string room_type_name { get; set; }
        public decimal room_cost { get; set; }
        public string room_type_description { get; set; }
        public bool room_smoke_friendly { get; set; }
        public bool room_pet_friendly { get; set; }
        public int rooms_in_the_room { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rooms> rooms { get; set; }
    }
}
