//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_list
    {
        public int task_list_id { get; set; }
        public int cleaning_name_id { get; set; }
        public int work_id { get; set; }
    
        public virtual cleaning_name cleaning_name { get; set; }
        public virtual works works { get; set; }
    }
}
