//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable
    {
        public int timetable_id { get; set; }
        public int employee_id { get; set; }
        public int room_id { get; set; }
        public System.DateTime cleaning_datetime { get; set; }
        public int cleaning_type_id { get; set; }
    
        public virtual cleaning_type cleaning_type { get; set; }
        public virtual rooms rooms { get; set; }
    }
}
