//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public int employee_id { get; set; }
        public int type_operation_id { get; set; }
        public System.DateTime date { get; set; }
        public string window_name { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual type_operation type_operation { get; set; }
    }
}
